# Generated by Django 2.2.2 on 2019-06-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercaption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecaption',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
