# Generated by Django 2.2.2 on 2019-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercaption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecaption',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
