# Generated by Django 2.2.2 on 2019-06-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercaption', '0002_auto_20190621_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecaption',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
