# Generated by Django 2.2.2 on 2019-06-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercaption', '0002_auto_20190619_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecaption',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
