# Generated by Django 2.2.2 on 2019-06-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercaption', '0003_auto_20190621_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecaption',
            name='image',
        ),
        migrations.AddField(
            model_name='imagecaption',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
