# Generated by Django 2.2.2 on 2019-06-21 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercaption', '0003_auto_20190621_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecaption',
            name='user',
        ),
    ]
