# Generated by Django 2.2.2 on 2019-06-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercaption', '0004_auto_20190621_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecaption',
            name='caption',
        ),
        migrations.AddField(
            model_name='imagecaption',
            name='image',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
