# Generated by Django 2.2.2 on 2019-06-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercaption', '0005_auto_20190621_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecaption',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='imagecaption',
            name='date',
        ),
    ]
