# Generated by Django 2.2.2 on 2019-06-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercaption', '0006_auto_20190621_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecaption',
            name='image',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
