# Generated by Django 2.2.2 on 2019-08-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercaption', '0008_auto_20190621_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecaption',
            old_name='caption',
            new_name='caption1',
        ),
        migrations.AddField(
            model_name='imagecaption',
            name='caption2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imagecaption',
            name='caption3',
            field=models.TextField(blank=True),
        ),
    ]
